site_name: Signal
site_url: https://opensource.bloom.sh
repo_url: https://github.com/bloom42/signal

site_dir: dist
docs_dir: pages

theme:
  name: null
  custom_dir: 'themes/mkdocs-material/material'
  language: en
  feature:
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

nav:
  - index.md
  - web.md
  - www.md
  - api.md
